# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee9df59a8d7c58954aeefad7c1964afc86481d4484a7db076e337b7c538acee935addfd5127ad61e9e30c9ba2851ff9cac7a8a4b52e1d31b63628221610681f6

test:
  secret_key_base: 0904bb57046bcd7fcdaf4b597552bc9ba3645e6595bacaf5cb982a384e7ba99a42da7332759bd1925e676509385523311e67150da564bb93da7b3a67a04754c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
